#pragma once
class Game;
class Pause;
class Title : public IGameObject
{
public:
	bool Start();
	void Update();
	void Render(RenderContext& rc);
	SpriteRender m_render;
	SpriteRender m_font;
	SpriteRender m_gauge;
	SpriteRender m_seafont;
	SpriteRender m_start;
	SpriteRender m_manual;
	SpriteRender m_b;
	SpriteRender m_optionButton;
	SpriteRender m_cameraOption;
	SpriteRender m_cameraCamera;
	SpriteRender m_charaCamera;
	SpriteRender m_bgmOption;
	SpriteRender m_bgmGauge;
	SpriteRender m_seOption;
	SpriteRender m_seGauge;
	SpriteRender m_masOption;
	SpriteRender m_masGauge;
	SpriteRender m_defaultOption;
	SpriteRender m_returnOption;
	SpriteRender m_arrow;
	Game* m_game;
	Pause* m_pause;
	SoundSource* m_sound;
	bool m_flug = false;
	bool m_gaugeflug = false;
	bool m_startAlpha = false;
	bool m_coolTime = false;
	bool m_manualAlpha = false;
	bool m_stopAlpha = false;
	bool m_optionState = false;
	bool m_optionMode = false;
	bool m_specialCamera = false;
	float m_count = 3.0f;
	float m_scare = 0.0f;
	float m_alpha = 1.0f;
	float m_hamachiAlpha = 1.0f;
	float m_fontHaikei = 0.0f;
	float m_startColor = 0.0f;
	float m_titleColor = 0.0f;
	float m_manualColor = 0.0f;
	float m_bColor = 0.0f;
	float m_stopColor = 1.0f;
	int m_i = 0;
	int m_j = 0;
	int m_newGame = 0;
	int m_se = 0;
	int m_3 = 0;
	int m_2 = 0;
	int m_1 = 0;
	int m_GO = 0;
	int m_sea = 0;
	int m_cool = 0;
	int m_optionSelecct = 0;
	int m_bgmVol = 10;
	int m_seVol = 10;
	int m_masVol = 7;
	int m_skyCubeType = enSkyCubeType_DayToon;
};
